apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-node-v1
spec:
  selector:
    matchLabels:
      app: service-node
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: service-node
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - name: service-node
        image: registry.cn-shanghai.aliyuncs.com/istio-test/service-node:v1
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 2
          timeoutSeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 2
          timeoutSeconds: 5
          periodSeconds: 3
---
kind: Service
apiVersion: v1
metadata:
  name: service-node
  labels:
    app: service-node
spec:
  selector:
    app: service-node
  ports:
    - name: http
      port: 80