# 根据源服务配置路由
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-go
spec:
  host: service-go
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-go
spec:
  hosts:
  - service-go
  http:
  - match:
    - sourceLabels:
        app: service-node
        version: v1
    route:
    - destination:
        host: service-go
        subset: v1
  - match:
    - sourceLabels:
        app: service-node
        version: v2
    route:
    - destination:
        host: service-go
        subset: v2