apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-js-v1
spec:
  selector:
    matchLabels:
      app: service-js
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: service-js
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - name: service-js
        image: registry.cn-shanghai.aliyuncs.com/istio-test/service-js:v1
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          timeoutSeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          timeoutSeconds: 5
          periodSeconds: 3
---
kind: Service
apiVersion: v1
metadata:
  name: service-js
  labels:
    app: service-js
spec:
  selector:
    app: service-js
  ports:
    - name: http
      port: 80